services:
  db:
    container_name: psql
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - proxynet

  backend:
    container_name: backend
    build: ./src/backend
    ports:
      - 5000:5000
    develop:
      watch:
        - action: sync
          path: ./src/backend
          target: /app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - proxynet

  frontend:
    build:
      target: ${BUILD_TARGET:-dev}
      context: ./src/frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_HOSTNAME: ${NEXT_PUBLIC_API_HOSTNAME}
      NEXT_PUBLIC_FRONTEND_HOSTNAME: ${NEXT_PUBLIC_FRONTEND_HOSTNAME}
      NEXT_PUBLIC_DARK_MODE: ${NEXT_PUBLIC_DARK_MODE}
    restart: always
    networks:
      - proxynet
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./src/frontend
          target: /app
          ignore:
            - node_modules/

volumes:
  db:
    name: markbib_db
    driver: local

networks:
  proxynet:
    name: custom_network